language: php

php:
  - '5.6'
  - '7.0'
env:
  global:
    - NODE_VERSION=7.9.0
    - NPM_VERSION=^5.0.0
    - BUILD_LEADER_ID=3
    - GITHUB_TOKEN=$GH_TOKEN
  matrix:
    - XDEBUG_VERSION=2.5.5

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - pecl install xdebug-$XDEBUG_VERSION
  - phpenv config-add travis-php.ini
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install -g npm@$NPM_VERSION --depth 0

install:
  - npm install

script:
  - npm run build
  - npm run lint
  - npm run cover

after_success:
  - 'nyc report --reporter=lcov > coverage.lcov && bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info'

jobs:
  include:
    - stage: test
      os: osx
      osx_image: xcode9.1
      language: generic
      before_install:
        # Fix ruby error https://github.com/Homebrew/brew/issues/3299
        - brew update
        - brew tap homebrew/homebrew-php
        - brew install php71
        - brew install homebrew/php/php71-xdebug
        - mkdir -p /usr/local/etc/php/7.1/conf.d
        - cp travis-php.ini /usr/local/etc/php/7.1/conf.d/
        - git clone --depth 1 https://github.com/creationix/nvm.git ./.nvm
        - source ./.nvm/nvm.sh
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - npm install -g npm@$NPM_VERSION --depth 0
    - stage: release
      language: node_js
      node_js: '8'
      before_install: skip
      install:
        - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
        - git fetch --tags
        - npm install
      script:
        - npm run build
      after_success:
        - npm run semantic-release

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

