language: php

php:
 - '5.4'
 - '5.6'
 - '7.0'

env:
  matrix:
    - XDEBUG_VERSION=stable
    - XDEBUG_VERSION=2.3.3

matrix:
  exclude:
    - env: XDEBUG_VERSION=2.3.3
      php: '7.0'

before_install:
 - pecl install xdebug-$XDEBUG_VERSION
 - phpenv config-add travis-php.ini
 - nvm install 5.10.0
 - nvm use 5.10.0
 - npm config -g set progress false
 - npm install -g typings

install:
 - npm install
 - typings install

script:
 - npm run compile --silent
 - npm run lint --silent
 - npm test --silent

sudo: false
